# Generated by Django 4.2.6 on 2024-01-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmsw', '0003_alter_param_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Images'),
        ),
    ]
