# Generated by Django 4.2.6 on 2024-01-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmsw', '0004_comment_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Image'),
        ),
    ]
