# Generated by Django 5.0 on 2025-11-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmsw', '0010_sysoption_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sysoption',
            name='value',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='sysoption',
            name='category',
            field=models.CharField(blank=True, choices=[('systems', 'Systems Parameters Integrations'), ('app', 'Application Parameters'), ('sidemenu', 'Side Menu'), ('topmenu', 'Top Menu'), ('prj', 'Project')], default='app', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='sysoption',
            name='desc',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='sysoption',
            name='json',
            field=models.TextField(blank=True, default='{}', max_length=75000, null=True),
        ),
        migrations.AlterField(
            model_name='sysoption',
            name='option',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
