# Generated by Django 5.0 on 2025-11-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmsw', '0011_sysoption_value_alter_sysoption_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='param',
            name='value',
            field=models.TextField(blank=True, default='', max_length=32000, null=True),
        ),
        migrations.AlterField(
            model_name='param',
            name='desc',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='param',
            name='json',
            field=models.TextField(blank=True, default='{}', max_length=75000, null=True),
        ),
        migrations.AlterField(
            model_name='param',
            name='option',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='sysoption',
            name='value',
            field=models.TextField(blank=True, default='', max_length=32000, null=True),
        ),
    ]
