# Generated by Django 4.2.26 on 2025-11-23 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appmsw', '0012_param_value_alter_param_desc_alter_param_json_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DbConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название подключения')),
                ('database_type', models.CharField(choices=[('postgresql', 'PostgreSQL'), ('oracle', 'Oracle')], max_length=20, verbose_name='Тип базы данных')),
                ('connection_string', models.CharField(max_length=500, verbose_name='Строка подключения JDBC')),
                ('username', models.CharField(max_length=100, verbose_name='Имя пользователя')),
                ('password', models.CharField(blank=True, max_length=200, verbose_name='Пароль')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Подключение к БД',
                'verbose_name_plural': 'Подключения к БД',
                'ordering': ['name'],
            },
        ),
    ]
