# Generated by Django 5.0 on 2025-11-25 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmsw', '0013_dbconnection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbconnection',
            name='database_type',
            field=models.CharField(choices=[('postgresql', 'PostgreSQL'), ('oracle', 'Oracle'), ('iris', 'IRIS')], max_length=20, verbose_name='Тип базы данных'),
        ),
    ]
